name: Keploy API Testing

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  keploy-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: anjali18
          POSTGRES_DB: booklibrary
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Download Keploy
        run: |
          curl -L https://github.com/keploy/keploy/releases/latest/download/keploy_linux_amd64.tar.gz | tar -xz
          sudo mv keploy /usr/local/bin/

      - name: Run Keploy Tests
        run: |
          nohup node server.js &
          sleep 10
          keploy test -c "node server.js" --delay 10
